In [1]:
import pandas as pd
import regex as re
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
## reading in county od for 2019 and 2020
countyod= pd.read_csv(r'C:\Users\darin\Documents\NSS\darina_capstone\capstone\data\2019.2020 _fatalod_bycounty.csv')
countyod

,Year,County Name,GeographyType,State,Type of Overdose,Total Number of Deaths
0,2019,Blount,County,TN,Involving Prescription Opioids,15
1,2019,Blount,County,TN,Involving All Opioids,34
2,2019,Blount,County,TN,Involving Opioids and Any Stimulant,10
3,2019,Blount,County,TN,Involving All Opioids and Benzodiazepines,3
4,2019,Bradley,County,TN,Involving Prescription Opioids,5
...,...,...,...,...,...,...
107,2020,Shelby,County,TN,Involving All Opioids and Benzodiazepines,105
108,2020,Washington,County,TN,Involving Prescription Opioids,12
109,2020,Washington,County,TN,Involving All Opioids,27
110,2020,Washington,County,TN,Involving Opioids and Any Stimulant,6
111,2020,Washington,County,TN,Involving All Opioids and Benzodiazepines,13

In [3]:
##dropping geographytype and state
countyod.drop(['GeographyType', 'State'], axis=1, inplace=True)
countyod

,Year,County Name,Type of Overdose,Total Number of Deaths
0,2019,Blount,Involving Prescription Opioids,15
1,2019,Blount,Involving All Opioids,34
2,2019,Blount,Involving Opioids and Any Stimulant,10
3,2019,Blount,Involving All Opioids and Benzodiazepines,3
4,2019,Bradley,Involving Prescription Opioids,5
...,...,...,...,...
107,2020,Shelby,Involving All Opioids and Benzodiazepines,105
108,2020,Washington,Involving Prescription Opioids,12
109,2020,Washington,Involving All Opioids,27
110,2020,Washington,Involving Opioids and Any Stimulant,6
111,2020,Washington,Involving All Opioids and Benzodiazepines,13

In [14]:
## isolating 2019 info
countyod2019= countyod.loc[countyod.Year == 2019]
countyod2019.head(1)

   Year County Name                Type of Overdose  Total Number of Deaths
0  2019      Blount  Involving Prescription Opioids                      15

In [15]:
countyod2019.drop(['Year'], axis=1, inplace=True)

C:\Users\darin\AppData\Local\Temp\ipykernel_10404\132471855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countyod2019.drop(['Year'], axis=1, inplace=True)

In [16]:
countyod2019

,County Name,Type of Overdose,Total Number of Deaths
0,Blount,Involving Prescription Opioids,15
1,Blount,Involving All Opioids,34
2,Blount,Involving Opioids and Any Stimulant,10
3,Blount,Involving All Opioids and Benzodiazepines,3
4,Bradley,Involving Prescription Opioids,5
5,Bradley,Involving All Opioids,16
6,Bradley,Involving Opioids and Any Stimulant,7
7,Bradley,Involving All Opioids and Benzodiazepines,3
8,Cocke,Involving Prescription Opioids,1
9,Cocke,Involving All Opioids,4
10,Cocke,Involving Opioids and Any Stimulant,1
11,Cocke,Involving All Opioids and Benzodiazepines,1
12,Davidson,Involving Prescription Opioids,78
13,Davidson,Involving All Opioids,280
14,Davidson,Involving Opioids and Any Stimulant,100
15,Davidson,Involving All Opioids and Benzodiazepines,54
16,Dyer,Involving Prescription Opioids,1
17,Dyer,Involving All Opioids,4
18,Dyer,Involving Opioids and Any Stimulant,3
19,Dyer,Involving All Opioids and Benzodiazepines,1
20,Hamilton,Involving Prescription Opioids,25
21,Hamilton,Involving All Opioids,72
22,Hamilton,Involving Opioids and Any Stimulant,35
23,Hamilton,Involving All Opioids and Benzodiazepines,2
24,Hardin,Involving Prescription Opioids,0
25,Hardin,Involving All Opioids,1
26,Hardin,Involving Opioids and Any Stimulant,1
27,Hardin,Involving All Opioids and Benzodiazepines,0
28,Henry,Involving Prescription Opioids,2
29,Henry,Involving All Opioids,5
30,Henry,Involving Opioids and Any Stimulant,3
31,Henry,Involving All Opioids and Benzodiazepines,4
32,Jackson,Involving Prescription Opioids,2
33,Jackson,Involving All Opioids,3
34,Jackson,Involving Opioids and Any Stimulant,1
35,Jackson,Involving All Opioids and Benzodiazepines,0
36,Knox,Involving Prescription Opioids,58
37,Knox,Involving All Opioids,187
38,Knox,Involving Opioids and Any Stimulant,80
39,Knox,Involving All Opioids and Benzodiazepines,24
40,Maury,Involving Prescription Opioids,7
41,Maury,Involving All Opioids,24
42,Maury,Involving Opioids and Any Stimulant,9
43,Maury,Involving All Opioids and Benzodiazepines,12
44,Montgomery,Involving Prescription Opioids,15
45,Montgomery,Involving All Opioids,62
46,Montgomery,Involving Opioids and Any Stimulant,19
47,Montgomery,Involving All Opioids and Benzodiazepines,9
48,Shelby,Involving Prescription Opioids,50
49,Shelby,Involving All Opioids,204
50,Shelby,Involving Opioids and Any Stimulant,87
51,Shelby,Involving All Opioids and Benzodiazepines,69
52,Washington,Involving Prescription Opioids,10
53,Washington,Involving All Opioids,16
54,Washington,Involving Opioids and Any Stimulant,4
55,Washington,Involving All Opioids and Benzodiazepines,8

In [17]:
countyod2019.groupby('County Name').sum()

C:\Users\darin\AppData\Local\Temp\ipykernel_10404\4112768704.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  countyod2019.groupby('County Name').sum()

             Total Number of Deaths
County Name
Blount                           62
Bradley                          31
Cocke                             7
Davidson                        512
Dyer                              9
Hamilton                        134
Hardin                            2
Henry                            14
Jackson                           6
Knox                            349
Maury                            52
Montgomery                      105
Shelby                          410
Washington                       38

In [18]:
totaldeaths_bycounty2019 =pd.DataFrame(countyod2019.groupby('County Name').sum())
totaldeaths_bycounty2019

C:\Users\darin\AppData\Local\Temp\ipykernel_10404\4125863966.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  totaldeaths_bycounty2019 =pd.DataFrame(countyod2019.groupby('County Name').sum())

             Total Number of Deaths
County Name
Blount                           62
Bradley                          31
Cocke                             7
Davidson                        512
Dyer                              9
Hamilton                        134
Hardin                            2
Henry                            14
Jackson                           6
Knox                            349
Maury                            52
Montgomery                      105
Shelby                          410
Washington                       38